onlyBuiltDependencies:
  - '@firebase/util'
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  jws@<3.2.3: '>=3.2.3'
  jws@=4.0.0: '>=4.0.1'
  next@>=16.0.0-canary.0 <16.0.7: '>=16.0.7'
  node-forge@<1.3.2: '>=1.3.2'
